---
unbalanced: !!bool true
clients:
  - max_num: !!int 10
  - timeouts:
      - type: !!str read
        value: !!int 10
      - type: !!str crit_read
        value: !!int 10
      - type: !!str write
        value: !!int 10
      - type: !!str crit_write
        value: !!int 10
L2_caches:
  - max_num: !!int 10
  - timeouts:
      - type: !!str read
        value: !!int 10
      - type: !!str crit_read
        value: !!int 10
      - type: !!str write
        value: !!int 10
      - type: !!str crit_write
        value: !!int 10
L1_caches:
  - max_num: !!int 10
  - timeouts:
      - type: !!str read
        value: !!int 10
      - type: !!str crit_read
        value: !!int 10
      - type: !!str write
        value: !!int 10
      - type: !!str crit_write
        value: !!int 10
database:
  - timeouts:
      - type: !!str refill
        value: !!int 10