systemProperty:
  unbalanced: !!bool false
  custom: !!bool true
clients:
  maxNum: !!int 10
  customNum: !!int 1
  timeouts:
    - type: !!str read
      value: !!int 100
    - type: !!str crit_read
      value: !!int 500
    - type: !!str write
      value: !!int 500
    - type: !!str crit_write
      value: !!int 120
    - type: !!str connection
      value: !!int 30
l2Caches:
  maxNum: !!int 10
  customNum: !!int 5
  timeouts:
    - type: !!str read
      value: !!int 45
    - type: !!str crit_read
      value: !!int 20
    - type: !!str write
      value: !!int 20
    - type: !!str crit_write
      value: !!int 60
l1Caches:
  maxNum: !!int 10
  customNum: !!int 3
  timeouts:
    - type: !!str response_data_recover
      value: !!int 80

database:
  timeouts:
    - type: !!str accepted_write
      value: !!int 20
    - type: !!str confirmed_write
      value: !!int 30