systemProperty:
  unbalanced: !!bool false
  custom: !!bool true
clients:
  maxNum: !!int 10
  customNum: !!int 1
  timeouts:
    - type: !!str read
      value: !!int 150
    - type: !!str crit_read
      value: !!int 200
    - type: !!str write
      value: !!int 250
    - type: !!str crit_write
      value: !!int 300
    - type: !!str connection
      value: !!int 30
l2Caches:
  maxNum: !!int 10
  customNum: !!int 5
  timeouts:
    - type: !!str read
      value: !!int 20
    - type: !!str crit_read
      value: !!int 30
    - type: !!str write
      value: !!int 40
    - type: !!str crit_write
      value: !!int 60
l1Caches:
  maxNum: !!int 10
  customNum: !!int 3
  timeouts:
    - type: !!str response_data_recover
      value: !!int 80

database:
  timeouts:
    - type: !!str accepted_write
      value: !!int 20
    - type: !!str confirmed_write
      value: !!int 30